### ISSUE TITLE
As a user I want to post a captioned picture

### ISSUE THREAD

**Issue by gaticosalas** [gaticosalas/SOEN341-IG-Clone#1]
Core Feature: Posting

Description: This core feature allows the user to post their own captioned picture to the main feed

Steps:

- Create a Post schema in the database
- Create Back-end CRUD routes for posts 
- Create client-side design for a post
- Create Front-end CRUD logic
  - Select picture from gallery
  - Add a caption
  - No editing allowed
  - Delete a post
 
Priority: Medium

**Comment by Joshua-Castillo** [comment]
Description: This core feature allows the user to post their own captioned picture to the main feed

Steps:
- design main feed for posts to be displayed on
- create post process 
        - select picture from gallery
        - add a caption to post
- assign post to user
- display post on feed
- remove post from feed 

Priority: High?
