### ISSUE TITLE
As a user I want to follow other users

### ISSUE THREAD

**Issue by gaticosalas** [gaticosalas/SOEN341-IG-Clone#2]
Core Feature: Following User Profiles

Description: This core feature allows, from the user's perspective, to select another user's profile, and follow them.

Steps:

- Create User and Profile schema in the database.
- Include link to other users in the Profile schema as "following".
- Create Back-end routes to register/login, find other users by username and add users to "following".
- Create client-side design for a profile
- Implement a Front-end username search and following system (linking to Back-end routes)

Priority: High

**Comment by loren589** [comment]
Core Feature: Following User Profiles

Description: This core feature allows, from the user's perspective, to select another user's profile, and follow them.

Steps:
 * User accesses account via login
 * Main feed displays recent posts from other users
 * User selects and follows another user profile from feed
 * Selected profile is tagged as 'followed' on user's UI

Priority: High
