### ISSUE TITLE
Create Login Form

### ISSUE THREAD

**Issue by gaticosalas** [gaticosalas/SOEN341-IG-Clone#9]
**MUST INCLUDE INPUTS**

- [x] email
- [x] password

Styling not necessary for now

**Comment by Joshua-Castillo** [comment]
if this is the landing page and the first page the user interacts with, might be good to have a register button too 

- [ ] register button

**Comment by gaticosalas** [comment]
@Joshua-Castillo yes! something like "don't have an account? Register"
