### ISSUE TITLE
As a user I want to be able to bookmark other people's posts

### ISSUE THREAD

**Issue by gaticosalas** [gaticosalas/SOEN341-IG-Clone#90]
Core Feature: Post Bookmarking.

Description: This core feature allows a user to save/bookmark other's posts and view them on his profile.

Steps:

1. Add bookmarks attributes to Profile schema in database [Risk: low, Value: High]
2. Link bookmarks to Post objects [Risk: low, Value: high]
3. Create Back-end routes for bookmarking [Risk: high, Value: high]
4. Create Front-end redux actions/reducer for bookmarks [Risk: high, Value: high]
5. Create a tab on the profile to display only the bookmarked posts [Risk: medium, Value, low]

Priority: High
Story Points: 7.6

**Comment by gaticosalas** [comment]
On a scale from 0 to 100, (100 being an Epic and very long/hard to do). Everyone give a number for the estimation of the effort required for this story.

I'll start: 5
reasoning: Most of the groundwork has already been made, only a few additions to the code are needed for this to work.

**Comment by MKB-1** [comment]
estimation: 8
reasoning: most of the features don't require much work. however it might require extra work to update the front end because things we have already done might need to be redesigned

**Comment by vishybala** [comment]
Effort req: 6
Reasoning: Profile and post models need little reworking to add this feature. Frontend would need a new tab that displays the collection.

**Comment by Joshua-Castillo** [comment]
On a scale from 0 to 100,

Effort: 10 
reasoning: The back-end algorithm for fetching the posts desired and sorting them is a relatively tricky, I previously had some difficulty filtering posts posts followed by user in Issue #74

**Comment by loren589** [comment]
Effort Estimation: 9

Reasoning:  The back-end aspect will most likely be the hardest part to implement, but the front end will only require minor adjustments to implement this.
