### ISSUE TITLE
Add a bookmark tab for the profile page

### ISSUE THREAD

**Issue by gaticosalas** [gaticosalas/SOEN341-IG-Clone#97]
edit the UI of the profile page to add tabs to switch from your posts to your bookmarked posts

**Comment by gaticosalas** [comment]
Story Points: 2

**Comment by Joshua-Castillo** [comment]
Story Points: 1

**Comment by vishybala** [comment]
Story Points: 2

**Comment by loren589** [comment]
Story Points: 2

**Comment by MKB-1** [comment]
story points: 2
